pariksha/teacher/routes.py
from flask import render_template,Blueprint,flash,redirect,url_for,request,send_from_directory
from flask_login import login_required,current_user,logout_user
from pariksha.models import Quiz,Quiz_Questions,Student
from pariksha import db
import datetime
import csv
import os

teacher = Blueprint('teacher',__name__,url_prefix="/teacher",template_folder='templates')


@teacher.route('/home')
@login_required
def home():
    if current_user.teacher is None:
        flash("Permission denied to access the page",'danger')
        return redirect(url_for('student.home'))
    return render_template('teacher_home.html',title = 'Home')


@teacher.route("/create_new_quiz")
@login_required
def create_new_quiz():
    if current_user.teacher is None:
        flash("Permission denied to access the page",'danger')
        return redirect(url_for('student.home'))
    return render_template('create_quiz.html',title = 'Create Quiz')


@teacher.route("/create_new_quiz", methods = ['POST'])
@login_required
def create_new_quiz_post():
    current_teacher = current_user.teacher
    response = request.form
    no_of_questions = int((len(response)-3)/6)
    total_marks = 0
    start_time = response['start_time']
    end_time = response['end_time']
    start_time = datetime.datetime.strptime(start_time,'%Y-%m-%d')
    end_time = datetime.datetime.strptime(end_time,'%Y-%m-%d')
    end_time += datetime.timedelta(seconds=24*60*60 - 1)


    quiz = Quiz(title = response['title'],start_time = start_time, end_time = end_time, teacher_id = current_teacher.id)
    for num in range(1,int(no_of_questions)+1):
        total_marks += int(response['Marks'+str(num)])
        question = Quiz_Questions(question_desc = response['Question'+str(num)] , option_1 = response['Option'+str(num)+'A'], option_2 = response['Option'+str(num)+'B'], option_3 = response['Option'+str(num)+'C'], option_4 = response['Option'+str(num)+'D'], marks = int(response['Marks'+str(num)]))
        question.quiz = quiz
        db.session.add(question)
    
    quiz.marks = total_marks
    db.session.add(quiz)
    db.session.commit()

    flash('The Quiz has been created', 'success')
    return redirect(url_for('teacher.home'))


@teacher.route('/activate_quiz_list')
@login_required
def activate_quiz_list():
    if current_user.teacher is None:
        flash('Access Denide','danger')
        return redirect(url_for('student.home'))
    teacher = current_user.teacher
    quiz_list = list(teacher.quiz_created)
    quiz_list = [quiz for quiz in quiz_list if quiz.start_time <= datetime.datetime.now() <= quiz.end_time]
    quiz_exists = bool(len(quiz_list))
    return render_template('quiz_list_activate.html',title = 'Activate Quiz', quiz_list = quiz_list, quiz_exists = quiz_exists)


@teacher.route('/activate_quiz/<int:quiz_id>')
@login_required
def activate_quiz(quiz_id):
    if current_user.teacher is None:
        flash('Access Denide','danger')
        return redirect(url_for('student.home'))
    teacher = current_user.teacher
    quiz = Quiz.query.filter_by(id = quiz_id).first_or_404()
    if quiz.teacher_id == teacher.id:
        quiz.active ^= 1
        db.session.commit()
        return redirect(url_for('teacher.activate_quiz_list'))
    else:
        return redirect(url_for('teacher.home'))

@teacher.route('/view_performance_list')
@login_required
def view_performance_list():
    if current_user.teacher is None:
        flash('Access Denied','danger')
        return redirect(url_for('student.home'))
    teacher = current_user.teacher
    quiz_list = list(teacher.quiz_created) 
    quiz_exists = bool(len(quiz_list))
    return render_template('quiz_list_teacher.html',title = 'View Performace', quiz_list = quiz_list, quiz_exists = quiz_exists)

@teacher.route('/view_performance/<int:quiz_id>', methods = ['POST','GET'])
@login_required
def view_performance(quiz_id):
    if current_user.teacher is None:
        flash('Access Denide','danger')
        return redirect(url_for('student.home'))
    quiz = Quiz.query.filter_by(id = quiz_id).first_or_404()
    teacher = current_user.teacher
    marks = list(db.session.execute(f'SELECT student_id,marks FROM submits_quiz WHERE quiz_id = {quiz_id}'))
    data = list()
    for i,entry in enumerate(marks):
        student_name = Student.query.filter_by(id = entry[0]).first().user.name
        data_entry = dict()
        data_entry['sr_no'] = i+1
        data_entry['student_id'] = entry[0]
        data_entry['student_name'] = student_name
        data_entry['marks'] = entry[1]
        data.append(data_entry)
    data_exists = bool(len(data))
    if request.method == 'POST':
        path = os.getcwd() + f'/pariksha/results/{quiz.title}_results.csv'
        try:
            with open(path,'w',newline='',encoding='utf-8') as file:
                field_names = list(data[0])
                writer = csv.DictWriter(file, fieldnames = field_names)
                writer.writeheader()
                for entry in data:
                    writer.writerow(entry)
            return send_from_directory(directory='results', filename=f'{quiz.title}_results.csv', as_attachment = True)
        except IOError:
            flash('Downloading Error Occured','warning')
            return redirect(url_for('teacher.home'))
    else:
        return render_template('view_quiz_performance.html',title = "View Performace", quiz_title = quiz.title, data = data)




    






    
    
    

pariksha/teacher/templates/quiz_list_activate.html
{% extends "layout.html" %}
{% block content%}
<style>
  .zoom {

    transition: transform .2s;
    /* Animation */
  }

  .zoom:hover {
    transform: scale(1.2);
    /* (150% zoom - Note: if the zoom is too large, it will go outside of the viewport) */
  }

  .button2:hover {
    box-shadow: 0 12px 16px 0 rgba(0, 0, 0, 0.24), 0 17px 50px 0 rgba(0, 0, 0, 0.19);
  }

  .po:hover {
    transition: transform .2s;
  }

  .po:hover {
    background-color: cyan;
  }
</style>

<div class="jumbotron" style="margin-top: 50px; background-color:white;">

  <div class="jumbotron" style=" background-color:pink; ">
    <!--the Pink box with border-->

    <!--<div class="jumbotron" style=" background-color:pink; border-radius:black solid;">-->
    <h2>All Your Quizzes Are Listed Below</h2>


  </div>
  <!-- The jumbotron just below this can be used as a container for whole the page and its contents-->
  <!-- ======  Start from here ======  -->

  {% if not(quiz_exists) %}


  <div class="jumbotron" style="background-color: white;  ">
    <div class="d-flex justify-content-center">
      <h1>No Quizzes Created</h1>
    </div>
    <div class="d-flex justify-content-center">
      <h3><a class="form-link" href="{{url_for('teacher.create_new_quiz')}}">Create Your First Quiz...</a><h3>
    </div>
  </div>
  <hr style="width:100%;text-align:left;margin-left:0; width:10px;">
  {% endif %}

  {% for quiz in quiz_list %}


  <div class="jumbotron" style="background-color: white;  height:150px;">

    <div class="example hoverable">

      <div class="container" >
        <div class="row" style=" height:0px; padding:0px; font-size:large; margin-top:-30px; border-radius:black solid;">
          <div class="col" id="po" style="background-color:mistyrose;border-radius:black solid;  ">
           <!-- blue  <div class="col" id="po" style="background-color:aqua;border-radius:black solid;  ">-->
           <!-- orange  <div class="col" id="po" style="background-color:coral;border-radius:black solid;  ">-->
           <!-- shadeinpink <div class="col" id="po" style="background-color:lightpink;border-radius:black solid;  ">-->
           <!-- shadeinorange  <div class="col" id="po" style="background-color:lightcoral;border-radius:black solid;  ">-->



            <h4 class="pt-3 pl-2"><strong>Quiz ID : {{quiz.id}} <span class="ml-5 pl-5"> {{quiz.title}}</span></strong>
            </h4>
            
          </div>
          <div class="col-md-auto" style="background-color:mistyrose; padding:20px;">
            <!-- shades in same occurrance match the above one here -->
            <!--<div class="col-md-auto" style="background-color:aqua; padding:20px;">-->
            <!--<div class="col-md-auto" style="background-color:coral; padding:20px;">-->
            <!--<div class="col-md-auto" style="background-color:lightpink; padding:20px;">-->
            <!--<div class="col-md-auto" style="background-color:lightcoral; padding:20px;">-->

              
          </div>
          

          
          <div class="col col-lg-2" style="background-color: mistyrose; padding:20px; ">
            <!-- Match here also -->
            <!--<div class="col col-lg-2" style="background-color: aqua; padding:20px; ">-->
            <!--<div class="col col-lg-2" style="background-color: coral; padding:20px; ">-->
            <!--<div class="col col-lg-2" style="background-color: lightpink; padding:20px; ">-->
            <!--<div class="col col-lg-2" style="background-color: lightcoral; padding:20px; ">-->
                {% if quiz.active %}
                <div class="example hoverable zoom">
                    <a type="button" class="btn btn-success" href="{{url_for('teacher.activate_quiz',quiz_id = quiz.id)}}"
                    style="width: 150px; margin-top:-4px; margin-left:px; background-color:#21a709f8;">Deactivate</a>
                </div>
                {% else %}
                    <div class="example hoverable zoom">
                        <a type="button" class="btn btn-success" href="{{url_for('teacher.activate_quiz',quiz_id = quiz.id)}}"
                        style="width: 150px; margin-top:-4px; margin-left:px; background-color:#e43c5c;">Activate</a>
                    </div>
                
                {% endif %}
            </div>
        </div>
    </div>
</div>
<hr style="width:100%;text-align:left;margin-left:0; width:10px;">
</div><!-- <==== end here-->
{% endfor %}





</div>

<footer class="page-footer blue text-center " style="padding: 15px; background-color:rgba(128, 128, 128, 0.199);">
    
    <!--Footer Links-->
    <div class="container-fluid" style="padding: 15px;">
        <div class="row">
            
            <!--First column-->
            <div class="col-md-6">
                <h5 class="title mb-3">PARiKSHA</h5>
                <p>
                    PARiKSHA is created with a motive of providing a unified platform to students and teachers so that the process of learning and its quality does not reduces in these tough times.
                    
                </p>
            </div>
            <!--/.First column-->
            
            <!--Second column-->
            <div class="col">
                <h5 class="title">Contact Us</h5>
                
                <li><a href="#">Mail</a></li>
                <p>pariksha.contact@gmail.com</p>
                <li><a href="https://www.linkedin.com/posts/pulkit-vyas_onlineexamination-onlineeducation-edtech-activity-6716777003296555008-MvzC">LinkedIn</a></li>
                
                
                
            </div>
            <!--/.Second column-->
        </div>
    </div>
    
</footer>



{% endblock content %}

pariksha/teacher/templates/quiz_list_teacher.html
{% extends "layout.html" %}
{% block content%}
<style>
  .zoom {

    transition: transform .2s;
    /* Animation */
  }

  .zoom:hover {
    transform: scale(1.2);
    /* (150% zoom - Note: if the zoom is too large, it will go outside of the viewport) */
  }

  .button2:hover {
    box-shadow: 0 12px 16px 0 rgba(0, 0, 0, 0.24), 0 17px 50px 0 rgba(0, 0, 0, 0.19);
  }

  .po:hover {
    transition: transform .2s;
  }

  .po:hover {
    background-color: cyan;
  }
</style>
<div class="jumbotron" style="margin-top: 50px; background-color:white;">

  <div class="jumbotron" style=" background-color:pink; ">
    <!--the Pink box with border-->

    <!--<div class="jumbotron" style=" background-color:pink; border-radius:black solid;">-->
    <h2>All Your Quizzes Are Listed Below</h2>


  </div>
  <!-- The jumbotron just below this can be used as a container for whole the page and its contents-->
  <!-- ======  Start from here ======  -->

  {% if not(quiz_exists) %}


  <div class="jumbotron" style="background-color: white;  ">
    <div class="d-flex justify-content-center">
      <h1>No Quizzes Created</h1>
    </div>
    <div class="d-flex justify-content-center">
      <h3><a class="form-link" href="{{url_for('teacher.create_new_quiz')}}">Create Your First Quiz...</a><h3>
    </div>
  </div>
  <hr style="width:100%;text-align:left;margin-left:0; width:10px;">
  {% endif %}

  {% for quiz in quiz_list %}


  <div class="jumbotron" style="background-color: white;  height:150px;">

    <div class="example hoverable">

      <div class="container" >
        <div class="row" style=" height:0px; padding:0px; font-size:large; margin-top:-30px; border-radius:black solid;">
          <div class="col" id="po" style="background-color:mistyrose;border-radius:black solid;  ">
           <!-- blue  <div class="col" id="po" style="background-color:aqua;border-radius:black solid;  ">-->
           <!-- orange  <div class="col" id="po" style="background-color:coral;border-radius:black solid;  ">-->
           <!-- shadeinpink <div class="col" id="po" style="background-color:lightpink;border-radius:black solid;  ">-->
           <!-- shadeinorange  <div class="col" id="po" style="background-color:lightcoral;border-radius:black solid;  ">-->



            <h4 class="pt-3 pl-2"><strong>Quiz ID : {{quiz.id}} <span class="ml-5 pl-5"> {{quiz.title}}</span></strong>
            </h4>
            
          </div>
          <div class="col-md-auto" style="background-color:mistyrose; padding:20px;">
            <!-- shades in same occurrance match the above one here -->
            <!--<div class="col-md-auto" style="background-color:aqua; padding:20px;">-->
            <!--<div class="col-md-auto" style="background-color:coral; padding:20px;">-->
            <!--<div class="col-md-auto" style="background-color:lightpink; padding:20px;">-->
            <!--<div class="col-md-auto" style="background-color:lightcoral; padding:20px;">-->

              
          </div>
          

          
          <div class="col col-lg-2" style="background-color: mistyrose; padding:20px; ">
            <!-- Match here also -->
            <!--<div class="col col-lg-2" style="background-color: aqua; padding:20px; ">-->
            <!--<div class="col col-lg-2" style="background-color: coral; padding:20px; ">-->
            <!--<div class="col col-lg-2" style="background-color: lightpink; padding:20px; ">-->
            <!--<div class="col col-lg-2" style="background-color: lightcoral; padding:20px; ">-->

            <div class="example hoverable zoom">
              <a type="button" class="btn btn-success" href="{{url_for('teacher.view_performance',quiz_id = quiz.id)}}"
                style="width: 150px; margin-top:-4px; margin-left:px; background-color:#e43c5c;">View Performance</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <hr style="width:100%;text-align:left;margin-left:0; width:10px;">
  </div><!-- <==== end here-->
  {% endfor %}





</div>

<footer class="page-footer blue text-center " style="padding: 15px; background-color:rgba(128, 128, 128, 0.199);">

  <!--Footer Links-->
  <div class="container-fluid" style="padding: 15px;">
      <div class="row">

          <!--First column-->
          <div class="col-md-6">
              <h5 class="title mb-3">PARiKSHA</h5>
              <p>
              PARiKSHA is created with a motive of providing a unified platform to students and teachers so that the process of learning and its quality does not reduces in these tough times.
                  
              </p>
          </div>
          <!--/.First column-->

          <!--Second column-->
          <div class="col">
              <h5 class="title">Contact Us</h5>
              
                  <li><a href="#">Mail</a></li>
                  <p>pariksha.contact@gmail.com</p>
                  <li><a href="https://www.linkedin.com/posts/pulkit-vyas_onlineexamination-onlineeducation-edtech-activity-6716777003296555008-MvzC">LinkedIn</a></li>
                  
                  
              
          </div>
          <!--/.Second column-->
      </div>
  </div>
 
</footer>





{% endblock content %}

pariksha/teacher/templates/teacher_home.html
{% extends "layout.html" %}
{% block content%}
<style>
  .zoom {

    transition: transform .2s;
    /* Animation */
  }

  .zoom:hover {
    transform: scale(1.2);
    /* (150% zoom - Note: if the zoom is too large, it will go outside of the viewport) */
  }

  .button2:hover {
    box-shadow: 0 12px 16px 0 rgba(0, 0, 0, 0.24), 0 17px 50px 0 rgba(0, 0, 0, 0.19);
  }
</style>
{% with messages = get_flashed_messages(with_categories = true ) %}
{% if messages %}
{% for category,message in messages %}
<div style="margin-top: 60px;" class="alert alert-{{category}}">
  <h3>{{message}}</h3>
</div>
{% endfor %}
{% endif %}
{% endwith %}
<div class="jumbotron" style="margin-top: 50px;">

  <div class="jumbotron" style=" background-color:pink; ">
    <h1>Welcome {{current_user.name}}!!</h1>
    <h3>Have a good day teacher!</h3>


  </div>
  <div class="row">

  </div>
  <div class="row row-cols-1 row-cols-sm-3 row-cols-md-8" style="margin-top: 50px;margin-left:70px;">
    <div class="col mb-1">


      <div class="card" style="width: 18rem; height: 23rem;">
        <div class="zoom">
          <img src="https://t4.ftcdn.net/jpg/02/20/89/49/240_F_220894919_dHe2SOXAdnjI4nt8td3ot4ZhmEmE6WRa.jpg"
            class="card-img-top" alt="..." style="width: 286px; height:190.66px;">
        </div>
        <div class="card-body">
          <h5 class="card-title">Create Test</h5>
          <p class="card-text">Create a new Quiz</p>
          <div class="zoom">
            <a href="{{url_for('teacher.create_new_quiz')}}" style="width: 15.25rem; margin-top:30px;" class="btn btn-danger">Create Test</a>
          </div>
        </div>
      </div>

    </div>
    <div class="col mb-5">

      <div class="card" style="width: 18rem; height: 23rem;">
        <div class="zoom">
          <img src="https://t3.ftcdn.net/jpg/03/06/14/50/240_F_306145094_fXSwGom0JWii8WKLqBMz5TL8G6X4EEPj.jpg"
            class="card-img-top" alt="..." style="width: 286px; height:190.66px;">
        </div>
        <div class="card-body">
          <h5 class="card-title">Activate Quizzes</h5>
          <p class="card-text">Activate or Deactivate Current Quizzes</p>
          <div class="zoom">
            <a href="{{url_for('teacher.activate_quiz_list')}}" style="width: 15.25rem; margin-top:5px;" class="btn btn-danger">Activate/Deactivate</a>
          </div>
        </div>
      </div>

    </div>
    
    <div class="col mb-5">

      <div class="card" style="width: 18rem; height: 23rem;">
        <div class="zoom">
          <img src="https://t4.ftcdn.net/jpg/03/32/93/91/240_F_332939130_xh4uVUk1lnxxaj6y3FHg2ivspzPEiSPW.jpg"
            class="card-img-top" alt="..." style="width: 286px; height:190.66px;">
        </div>
        <div class="card-body">
          <h5 class="card-title">View Performance</h5>
          <p class="card-text">Check how your class performed.</p>
          <div class="zoom">

            <a href="{{url_for('teacher.view_performance_list')}}" style="width: 15.25rem; margin-top:6px;" class="btn btn-danger">Check Result</a>
          </div>
        </div>
      </div>





    </div>
  </div>
</div>
</div>
<footer class="page-footer blue text-center " style="padding: 15px; background-color:rgba(128, 128, 128, 0.199);">

  <!--Footer Links-->
  <div class="container-fluid" style="padding: 15px;">
      <div class="row">

          <!--First column-->
          <div class="col-md-6">
              <h5 class="title mb-3">PARiKSHA</h5>
              <p>
              PARiKSHA is created with a motive of providing a unified platform to students and teachers so that the process of learning and its quality does not reduces in these tough times.
                  
              </p>
          </div>
          <!--/.First column-->

          <!--Second column-->
          <div class="col">
              <h5 class="title">Contact Us</h5>
              
                  <li><a href="#">Mail</a></li>
                  <p>pariksha.contact@gmail.com</p>
                  <li><a href="https://www.linkedin.com/posts/pulkit-vyas_onlineexamination-onlineeducation-edtech-activity-6716777003296555008-MvzC">LinkedIn</a></li>
                  
                  
              
          </div>
          <!--/.Second column-->
      </div>
  </div>
 
</footer>


{% endblock content %}

pariksha/teacher/templates/teacher_input1.html
{% extends "layout.html" %}
{% block content%}

<head>


    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>
<style>
    .zoom {

        transition: transform .2s;

    }

    .zoom:hover {
        transform: scale(1.2);

    }

    .button2:hover {
        box-shadow: 0 12px 16px 0 rgba(0, 0, 0, 0.24), 0 17px 50px 0 rgba(0, 0, 0, 0.19);
    }

    .po:hover {
        transition: transform .2s;
    }

    .po:hover {
        background-color: cyan;
    }





    .btn-file {
        position: relative;
        overflow: hidden;
    }

    .btn-file input[type=file] {
        position: absolute;
        top: 0;
        right: 0;
        min-width: 100%;
        min-height: 100%;
        font-size: 100px;
        text-align: right;
        filter: alpha(opacity=0);
        opacity: 0;
        outline: none;
        background: white;
        cursor: inherit;
        display: block;
    }

    #img-upload {
        width: 100%;
    }
</style>
<form method="POST">
    <div class="jumbotron" style="margin-top: 50px;">



        <div class="jumbotron" style=" background-color:pink; ">

            <h2>
                Add all the questions here that you want to see in your <strong>Quiz</strong>
            </h2>
            <hr style="width:100%;text-align:left;margin-left:0">
            <h5>Some instructions:</h5>
            <ul>Enter the correct answer in the first text area option</ul>
            <ul>The options would be shuffled for all the students</ul>
            <hr style="width:100%;text-align:left;margin-left:0">

            <!-- <<<<=============================This is the form tag i added- ===============================================>>> -->

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <!--############################### V Quiz title date-->
                    <span class="input-group-text" id="Quiztitle-addon1">Quiz Title</span>
                </div>

                <textarea id="Quiz_title" name="title" rows="1" cols="50" style="border-radius: 5px; border:double;"
                    aria-label="Question" placeholder="Enter the quiz title"></textarea>

            </div>


            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <!-- ############################## start date tag V-->
                    <span class="input-group-text" id="Start_date-addon1">Start Date</span>
                </div>

                <input type="date" name='start_time'>


            </div>

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <!--############################### V end date tag-->
                    <span class="input-group-text" id="End_date-addon1">End Date</span>
                </div>

                <input type="date" name='end_time'>

            </div>

        </div>



        <!-- <blockquote class="imgur-embed-pub" lang="en" data-id="P36epN6"  ><a href="//imgur.com/P36epN6"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>
   -->

        <div class="jumbotron">

            <!-- <==========Start Cloning from here-->
            <div class="container" style="background-color: coral; padding:20px; border-radius:30px; margin-top:50px;"
                id="form_instance1">
                <div class="input-group mb-3" style="padding: 10px;">

                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Question</span>
                        </div>

                        <textarea id="QuesIn" name="Question1" rows="3" cols="106"
                            style="border-radius: 5px; border:double;" aria-label="Question"
                            placeholder="Enter Your Your Question" class='mt-2'></textarea>

                    </div>

                    <div class="col">
                        <div style="padding: 10px;">
                            <div class="input-group">
                                <input type="text" name="Option1A" class="form-control"
                                    aria-label="Text input with radio button" id="OptionA">
                            </div>
                        </div>

                        <div style="padding: 10px;">
                            <div class="input-group">

                                <input type="text" name="Option1B" class="form-control"
                                    aria-label="Text input with radio button" id="OptionB">
                            </div>
                        </div>

                        <div style="padding: 10px;">
                            <div class="input-group">

                                <input type="text" name="Option1C" class="form-control"
                                    aria-label="Text input with radio button" id="OptionC">
                            </div>
                        </div>

                        <div style="padding: 10px;">
                            <div class="input-group">

                                <input type="text" name="Option1D" class="form-control"
                                    aria-label="Text input with radio button" id="OptionD">
                            </div>
                        </div>
                        <div class="input-group-prepend" style="margin-left: 10px;">
                            <!--############################### V enter marks tag-->
                            <span class="input-group-text" id="Enter_Marks-addon1">Enter marks for question</span>
                            <input type="number" min=1 style="width: 50px;" value="1" name="Marks1" id="Marks" />

                        </div>




                    </div>
                </div>
            </div>
        </div>

        <div class="row justify-content-center">


            <div class="example hoverable">
                <button type="button" class="btn btn-danger"
                    style="width: 150px; margin-top:-4px; background-color:#e43c5c;" id="clone_btn">
                    Add Question
                </button>
            </div>



        </div>
        <hr style="width:100%;text-align:left;margin-left:0">

        <!-- <==== Clone till here-->
        <div class="row justify-content-end">
            <div class="example hoverable">
                <input type="submit" value="Submit" class="btn btn-danger"
                    style="width: 150px; margin-top:-4px; background-color:#e43c5c; margin-left:40px;">
            </div>
        </div>
</form><!-- <======= Form tag end ========>-->








<script>

    $(document).ready(function () {
        $(document).on('change', '.btn-file :file', function () {
            var input = $(this),
                label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
            input.trigger('fileselect', [label]);
        });

        $('.btn-file :file').on('fileselect', function (event, label) {

            var input = $(this).parents('.input-group').find(':text'),
                log = label;

            if (input.length) {
                input.val(log);
            } else {
                if (log) alert(log);
            }

        });
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#img-upload').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#imgInp").change(function () {
            readURL(this);
        });
    });
</script>

<script>
    $('#clone_btn').click(function () {
        var $div = $('div[id^="form_instance"]:last');
        var num = parseInt($div.prop("id").match(/\d+/g), 10) + 1;
        var $clone = $div.clone().prop('id', 'form_instance' + num);
        $div.after($clone);
        $clone.find('#QuesIn').attr('name', 'Question' + num);
        $clone.find('#Marks').attr('name', 'Marks' + num);
        $clone.find('#OptionA').attr('name', 'Option' + num + 'A');
        $clone.find('#OptionB').attr('name', 'Option' + num + 'B');
        $clone.find('#OptionC').attr('name', 'Option' + num + 'C');
        $clone.find('#OptionD').attr('name', 'Option' + num + 'D');
        $clone.find('#imgInp').attr('name', 'photo-url' + num);
        $clone.find("input[type='number']").val('');
        $clone.find("input[type='text']").val('');
        $clone.find("textarea").val('');
        $clone.find("#imgInp").val('');
    });
</script>


<footer class="page-footer blue text-center " style="margin-top:80px;background-color:rgba(128, 128, 128, 0.199);">

    <!--Footer Links-->
    <div class="container-fluid" style="padding: 15px;">
        <div class="row">

            <!--First column-->
            <div class="col-md-6">
                <h5 class="title mb-3">PARiKSHA</h5>
                <p>
                    PARiKSHA is created with a motive of providing a unified platform to students and teachers so that
                    the process of learning and its quality does not reduces in these tough times.

                </p>
            </div>
            <!--/.First column-->

            <!--Second column-->
            <div class="col">
                <h5 class="title">Contact Us</h5>

                <li><a href="#">Mail</a></li>
                <p>pariksha.contact@gmail.com</p>
                <li><a
                        href="https://www.linkedin.com/posts/pulkit-vyas_onlineexamination-onlineeducation-edtech-activity-6716777003296555008-MvzC">LinkedIn</a>
                </li>



            </div>
            <!--/.Second column-->
        </div>
    </div>

</footer>


{% endblock content %}