pariksha/student/routes.py
from flask import render_template,Blueprint,redirect,url_for,request,flash
from flask_login import login_required,current_user,logout_user
from pariksha import db
from pariksha.student.utils import shuffle,random
from pariksha.models import Student,Teacher,Quiz
from pariksha.student.utils import bar_graph
import copy



student = Blueprint("student",__name__,url_prefix="/student" ,template_folder="templates",static_folder="static")

@student.route("/home")
@login_required
def home():
    quotes = ["Let us study things that are no more. It is necessary to understand them, if only to avoid them.","The authority of those who teach is often an obstacle to those who want to learn","To acquire knowledge, one must study; but to acquire wisdom, one must observe."]
    random.shuffle(quotes)
    if current_user.student is None:
        logout_user()
        #return error page ERROR 403
        return "unauthorized acess attempted you have been logged out"
    return render_template("student_home.html",quotes = quotes, title = "Home")

@student.route("/quiz/<int:quiz_id>")
@login_required
def quiz(quiz_id):
    if current_user.student is None:
        logout_user()
        return redirect(url_for('main.welcome'))
    quiz = Quiz.query.filter_by(id = quiz_id).first_or_404()
    if quiz in current_user.student.submitted_quiz:
        flash('You have already submitted this quiz!!','warning')
        return redirect(url_for('student.home'))
    teacher_id_list = [teacher.id for teacher in current_user.student.taught_by.all()]
    if quiz.teacher_id not in teacher_id_list:
        flash("You are not allowed to access the page you requested","warning")
        return redirect(url_for('student.home'))
    if not quiz.active:
        flash("The quiz you are trying to attemp is not active right now","warning")
        return redirect(url_for('student.home'))
    
    questions = quiz.questions
    orig_questions = dict()
    index = 1
    for question in questions:
        orig_questions[ str(question.question_desc)] = [str(question.option_1),str(question.option_2),str(question.option_3),str(question.option_4)]
        index += 1


    questions = copy.deepcopy(orig_questions)
    shuffled_q = shuffle(questions)

    for i in questions.keys():
        random.shuffle(questions[i])
    
    question_count = len(orig_questions)

    return render_template('quiz.html', title = quiz.title, shuffled_questions = shuffled_q , questions = questions, question_count = question_count)

@student.route("/quiz/<int:quiz_id>", methods = ["POST"])
@login_required
def quiz_post(quiz_id):

    quiz = Quiz.query.filter_by(id = quiz_id).first_or_404()
    if not quiz.active:
        flash('QUIZ NOT SUBMITTED The quiz you are trying to submit has expired','danger')
        return redirect(url_for('student.home'))
    if quiz in current_user.student.submitted_quiz:
        flash('You have already submitted this quiz!!','warning')
        return redirect(url_for('student.home'))
    questions = quiz.questions
    orig_questions = dict()
    orig_questions_marks = dict()
    for question in questions:
        orig_questions[str(question.question_desc)] = [str(question.option_1),str(question.option_2),str(question.option_3),str(question.option_4)]
        orig_questions_marks[str(question.question_desc)] = question.marks
    
    questions = copy.deepcopy(orig_questions)

    marks = 0
    for i in questions.keys():
        answered = request.form[i]
        if orig_questions[i][0] == answered:
            marks += orig_questions_marks[i]
    
    current_user.student.submitted_quiz.append(quiz)
    db.session.commit()
    db.session.execute(f'UPDATE submits_quiz SET marks = {marks} WHERE student_id = {current_user.student.id} and quiz_id = {quiz_id};')
    db.session.commit()
    flash(f'Your response for Quiz : {quiz.title} has been submitted','success')
    return redirect(url_for('student.home'))

@student.route("/list_quiz")
@login_required
def list_quiz():
    if current_user.student is None:
        flash('Access Denied','danger')
        return redirect(url_for('teacher.home'))
    teachers_lis = current_user.student.taught_by.all()
    quiz_list = [quiz for teacher in teachers_lis for quiz in teacher.quiz_created]
    quiz_list = [quiz for quiz in quiz_list if quiz.active]
    quiz_exists = bool(len(quiz_list))
    return render_template('quiz_list.html',quiz_list = quiz_list,quiz_exists = quiz_exists, title = "Quizzes")


@student.route("/view_performance")
@login_required
def view_performance():
    if current_user.student is None:
        flash('Access Denied','danger')
        return redirect(url_for('teacher.home'))
    student = current_user.student
    quiz_submitted_query = tuple(db.session.execute(f'SELECT * FROM submits_quiz WHERE student_id = {student.id};'))
    quiz_submitted = list()
    
    for quiz in quiz_submitted_query:
        quiz_title = Quiz.query.filter_by(id = quiz[1]).first().title
        all_marks = list(db.session.execute(f'SELECT marks FROM submits_quiz WHERE quiz_id = {quiz[1]}'))
        all_marks = [x[0] for x in all_marks]
        quiz_submitted.append(dict(quiz_title = quiz_title,marks = quiz[3],all_marks = all_marks ))
    graph = bar_graph(quiz_submitted)

    return render_template('view_performance.html',graph = graph, title = 'Your Performance')
   
@student.route('/view_result')
@login_required
def view_result():
    if current_user.student is None:
        flash('Access Denied','danger')
        return redirect(url_for('teacher.home'))
    student = current_user.student
    quiz_submitted_query = tuple(db.session.execute(f'SELECT * FROM submits_quiz WHERE student_id = {student.id};'))
    quiz_submitted = list()
    
    for quiz in quiz_submitted_query:
        quiz_title = Quiz.query.filter_by(id = quiz[1]).first().title
        total_marks = Quiz.query.filter_by(id = quiz[1]).first().marks
        quiz_submitted.append(dict(title = quiz_title,marks = quiz[3],total_marks = total_marks))

    quiz_exists = bool(len(quiz_submitted))
    return render_template('view_result.html',quiz_list = quiz_submitted, title = "View Result", quiz_exists = quiz_exists)



    
@student.route('/add_teacher', methods = ['GET','POST'])
@login_required
def add_teacher():
    if current_user.student is None:
        flash('Access Denied','danger')
        return redirect(url_for('teacher.home'))
    if request.method == 'GET':
        return render_template('add_teacher.html',title = 'Add Teacher')
    if request.method == 'POST':
        teacher_id = request.form['teacher_id']
        teacher = Teacher.query.filter_by(id = teacher_id).first()
        if teacher is None:
            flash(f'Teacher with teacher id {teacher_id} does not exist','danger')
            return redirect(url_for('student.add_teacher'))
        if current_user.student in teacher.students:
            flash('The teacher is already added','info')
            return redirect(url_for('student.add_teacher'))
        teacher.students.append(current_user.student)
        db.session.commit()
        flash('Teacher has been added','success')
        return redirect(url_for('student.add_teacher'))
            
        

pariksha/student/templates/add_teacher.html
{% extends "layout.html" %}
{% block content%}


{% with messages = get_flashed_messages(with_categories = true ) %}
        {% if messages %}
        {% for category,message in messages %}
        <div  class=" alert alert-{{category}} mt-5 ">
          <h3 style="padding-top: 5px; text-align: center;">{{message}}</h3>
        </div>
        {% endfor %}
        {% endif %}
  {% endwith %}
<div class="jumbotron" style="margin-top: 50px;  height: 100%;


background-position: center;
background-repeat: no-repeat;
background-size: cover;
padding:70px;">

    <div class="col" style="padding: px;">

        <div class="container" style="background-color:white; border-radius:30px; margin-top:50px; margin-bottom: 250px;">
            <h2 style="text-align: center;"><strong>ADD TEACHER</strong></h2>
            <h4 style="text-align: center;">Enter the unique ID of your teacher to be able to access the quizzes created by them</h4>

            <hr style="width:100%;text-align:left;margin-left:0">

            <form method="POST">

                <div class="container" style="padding:20px;">
                    <label for="basic-ul">Enter the teacher id </label>
                    <div class="input-group ">
                        
                        <input type="number" required min=1 class="form-control" id="teacher_id" name="teacher_id"
                        aria-describedby="basic-addon3" placeholder="Enter the Id here ">
                    </div>
                </div>
                <div class="row justify-content-center" style="margin-top: 20px; color:blue; padding:20px;">
                    <button class="btn btn-primary btn-lg " type="submit">Submit</button>
                </div>
            </form>

        </div>
        
    </div>
</div>

<footer class="page-footer blue text-center " style="padding: 15px; background-color:rgba(128, 128, 128, 0.199);">

    <!--Footer Links-->
    <div class="container-fluid" style="padding: 15px;">
        <div class="row">
  
            <!--First column-->
            <div class="col-md-6">
                <h5 class="title mb-3">PARiKSHA</h5>
                <p>
                PARiKSHA is created with a motive of providing a unified platform to students and teachers so that the process of learning and its quality does not reduces in these tough times.
                    
                </p>
            </div>
            <!--/.First column-->
  
            <!--Second column-->
            <div class="col">
                <h5 class="title">Contact Us</h5>
                
                    <li><a href="#">Mail</a></li>
                    <p>pariksha.contact@gmail.com</p>
                    <li><a href="https://www.linkedin.com/posts/pulkit-vyas_onlineexamination-onlineeducation-edtech-activity-6716777003296555008-MvzC">LinkedIn</a></li>
                    
                    
                
            </div>
            <!--/.Second column-->
        </div>
    </div>
   
  </footer>
  

{% endblock content %}

pariksha/student/templates/quiz_list.html
{% extends "layout.html" %}
{% block content%}
<style>
  .zoom {

    transition: transform .2s;
    /* Animation */
  }

  .zoom:hover {
    transform: scale(1.2);
    /* (150% zoom - Note: if the zoom is too large, it will go outside of the viewport) */
  }

  .button2:hover {
    box-shadow: 0 12px 16px 0 rgba(0, 0, 0, 0.24), 0 17px 50px 0 rgba(0, 0, 0, 0.19);
  }

  .po:hover {
    transition: transform .2s;
  }

  .po:hover {
    background-color: cyan;
  }


</style>
<div class="jumbotron" style="margin-top: 50px; background-color:white;">

  <div class="jumbotron" style=" background-color:pink; ">
    <!--the Pink box with border-->

    <!--<div class="jumbotron" style=" background-color:pink; border-radius:black solid;">-->
    <h2>All Active Quizzes are Listed Below</h2>


  </div>
  <!-- The jumbotron just below this can be used as a container for whole the page and its contents-->
  <!-- ======  Start from here ======  -->

  {% if not(quiz_exists) %}


  <div class="jumbotron" style="background-color: white;  ">
    <div class="d-flex justify-content-center">
      <h1>No Active Quizzes Right Now</h1>
    </div>
    <div class="d-flex justify-content-center">
      <h3>Please refresh if you are expecting a quiz right now...<h3>
    </div>
  </div>
  <hr style="width:100%;text-align:left;margin-left:0; width:10px;">
  {% endif %}

  {% for quiz in quiz_list %}


  <div class="jumbotron" style="background-color:rgba(128, 128, 128, 0.096); ">

    <div class="example hoverable">

      <div class="container">
        <div class="row"
          style=" height:0px; padding:0px; font-size:large; margin-top:-30px; border-radius:black solid;">
          <div class="col" id="po" style="background-color:mistyrose;border-radius:black solid;  ">
            <!-- blue  <div class="col" id="po" style="background-color:aqua;border-radius:black solid;  ">-->
            <!-- orange  <div class="col" id="po" style="background-color:coral;border-radius:black solid;  ">-->
            <!-- shadeinpink <div class="col" id="po" style="background-color:lightpink;border-radius:black solid;  ">-->
            <!-- shadeinorange  <div class="col" id="po" style="background-color:lightcoral;border-radius:black solid;  ">-->



            <h4 class="pt-3 pl-2"><strong>Quiz ID : {{quiz.id}} <span class="ml-5 pl-5"> {{quiz.title}}</span></strong>
            </h4>

          </div>
          <div class="col-md-auto" style="background-color:mistyrose; padding:20px;">
            <!-- shades in same occurrance match the above one here -->
            <!--<div class="col-md-auto" style="background-color:aqua; padding:20px;">-->
            <!--<div class="col-md-auto" style="background-color:coral; padding:20px;">-->
            <!--<div class="col-md-auto" style="background-color:lightpink; padding:20px;">-->
            <!--<div class="col-md-auto" style="background-color:lightcoral; padding:20px;">-->


          </div>



          <div class="col col-lg-2" style="background-color: mistyrose; padding:20px; ">
            <!-- Match here also -->
            <!--<div class="col col-lg-2" style="background-color: aqua; padding:20px; ">-->
            <!--<div class="col col-lg-2" style="background-color: coral; padding:20px; ">-->
            <!--<div class="col col-lg-2" style="background-color: lightpink; padding:20px; ">-->
            <!--<div class="col col-lg-2" style="background-color: lightcoral; padding:20px; ">-->

            <div class="example hoverable zoom">
              <a type="button" class="btn btn-success" href="{{url_for('student.quiz',quiz_id = quiz.id)}}"
                style="width: 150px; margin-top:-4px; margin-left:px; background-color:#e43c5c;">Attempt</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <hr style="width:100%;text-align:left;margin-left:0; width:10px;">
  </div><!-- <==== end here-->
  {% endfor %}
  </div>

  <footer class="page-footer blue text-center " style="padding: 15px; position: bottom; left: 0; bottom: 0; width: 100%; background-color:rgba(128, 128, 128, 0.199);">
    
    <!--Footer Links-->
    <div class="container-fluid" style="padding: 15px;">
        <div class="row">
  
            <!--First column-->
            <div class="col-md-6">
                <h5 class="title mb-3">PARiKSHA</h5>
                <p>
                PARiKSHA is created with a motive of providing a unified platform to students and teachers so that the process of learning and its quality does not reduces in these tough times.
                    
                </p>
            </div>
            <!--/.First column-->
  
            <!--Second column-->
            <div class="col">
                <h5 class="title">Contact Us</h5>
                
                    <li><a href="#">Mail</a></li>
                    <p>pariksha.contact@gmail.com</p>
                    <li><a href="https://www.linkedin.com/posts/pulkit-vyas_onlineexamination-onlineeducation-edtech-activity-6716777003296555008-MvzC">LinkedIn</a></li>
                    
                    
                
            </div>
            <!--/.Second column-->
        </div>
    </div>
   
  </footer>
  






{% endblock content %}

pariksha/student/templates/quiz_list_old.html
{% extends "layout.html" %}
{% block content%}
<style>
  .zoom {

    transition: transform .2s;
    /* Animation */
  }

  .zoom:hover {
    transform: scale(1.2);
    /* (150% zoom - Note: if the zoom is too large, it will go outside of the viewport) */
  }

  .button2:hover {
    box-shadow: 0 12px 16px 0 rgba(0, 0, 0, 0.24), 0 17px 50px 0 rgba(0, 0, 0, 0.19);
  }

  .po:hover{
      transition: transform .2s;
  }
  .po:hover
  {
      background-color: cyan;
  }
</style>
<div class="jumbotron" style="margin-top: 50px;">

  <div class="jumbotron" style=" background-color:pink; ">
    
    <h2>Quizes</h2>


  </div>
  {% for quiz in quiz_lis %}
    
  <div class="jumbotron">
    <div class="example hoverable">
      <div class="row" style="background-color: coral; height:50px; padding:10px; font-size:large;">
        <div class="col" id="po" style="background-color: coral; ">
          <strong ><a href="#">{{quiz.title}}</a></strong>
        </div>
        <div class="col-md-auto" style="background-color: coral; ">
          <div>
            {{quiz.start_time}}
          </div>
          <div>Submitted:</div>
          {% if quiz.submitted == True %}
          <div>
            <img src="https://i1.wp.com/nahbnow.com/wp-content/uploads/2018/08/iStock-692279620.jpg" style="height:30px; ">
          </div>
          {% else %}
          <div >
            <img src="https://www.pinclipart.com/picdir/big/532-5329134_computer-icons-x-mark-clip-art-red-cross.png" style="height:30px; ">
          </div>
          {% endif %}
        </div>
        <div class="col col-lg-2"style="background-color: coral; ">
          <div class="example hoverable zoom">
            <a type="button" class="btn btn-danger" href = "{{url_for('main.welcome')}}" style="width: 150px; margin-top:-4px; margin-left:50px; background-color:e43c5c;">Attempt</a>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% endfor %}
  <footer class="page-footer blue text-center " style="padding: 15px; background-color:rgba(128, 128, 128, 0.199);">

    <!--Footer Links-->
    <div class="container-fluid" style="padding: 15px;">
        <div class="row">
  
            <!--First column-->
            <div class="col-md-6">
                <h5 class="title mb-3">PARiKSHA</h5>
                <p>
                PARiKSHA is created with a motive of providing a unified platform to students and teachers so that the process of learning and its quality does not reduces in these tough times.
                    
                </p>
            </div>
            <!--/.First column-->
  
            <!--Second column-->
            <div class="col">
                <h5 class="title">Contact Us</h5>
                
                    <li><a href="#">Mail</a></li>
                    <p>pariksha.contact@gmail.com</p>
                    <li><a href="https://www.linkedin.com/posts/pulkit-vyas_onlineexamination-onlineeducation-edtech-activity-6716777003296555008-MvzC">LinkedIn</a></li>
                    
                    
                
            </div>
            <!--/.Second column-->
        </div>
    </div>
   
  </footer>
  
{% endblock content %}

pariksha/student/templates/student_home.html
{% extends "layout.html" %}
{% block content%}
<style>
  .zoom {

    transition: transform .2s;
    /* Animation */
  }

  .zoom:hover {
    transform: scale(1.2);
    /* (150% zoom - Note: if the zoom is too large, it will go outside of the viewport) */
  }

  .button2:hover {
    box-shadow: 0 12px 16px 0 rgba(0, 0, 0, 0.24), 0 17px 50px 0 rgba(0, 0, 0, 0.19);
  }
</style>
{% with messages = get_flashed_messages(with_categories = true ) %}
{% if messages %}
{% for category,message in messages %}
<div style="margin-top: 70px;" class="alert alert-{{category}}">
  <h3>{{message}}</h3>
</div>
{% endfor %}
{% endif %}
{% endwith %}
<div class="jumbotron" style="margin-top: 50px;  background-color:rgba(128, 128, 128, 0.199);">

  <div class="jumbotron" style=" background-color:pink; ">
    <h1>Welcome {{current_user.name}} !!</h1>
    <h3><strong> Quote of the day</strong> : {{quotes[0]}}</h3>


  </div>
  <div class="row">

  </div>
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4" style="margin-top: 50px;;">
    <div class="col mb-1">


      <div class="card" style="width: 18rem; height: 23rem;">
        <div class="zoom">
          <img src="https://t3.ftcdn.net/jpg/02/34/37/84/240_F_234378496_LK9HJn2cdCq1zSKr19c8NwqDYgy2ouHz.jpg"
            class="card-img-top" alt="...">
        </div>
        <div class="card-body">
          <h5 class="card-title">Attempt Quiz</h5>
          <p class="card-text">Click on the button below to view all active quizzes</p>
          <div class="zoom">
            <a href="{{url_for('student.list_quiz')}}" style="width: 15.25rem; margin-top:5px;"
              class="btn btn-danger">Attemp Quiz</a>
          </div>
        </div>
      </div>

    </div>
    <div class="col mb-4">

      <div class="card" style="width: 18rem; height: 23rem;">
        <div class="zoom">
          <img src="https://t3.ftcdn.net/jpg/03/78/17/94/240_F_378179426_fanID4R9NLWcuenQSwio4f3mttmvUJfz.jpg"
            class="card-img-top" alt="...">
        </div>
        <div class="card-body">
          <h5 class="card-title">View Result</h5>
          <p class="card-text">View your marks</p>
          <div class="zoom">
            <a href="{{url_for('student.view_result')}}" style="width: 15.25rem; margin-top:30px;" class="btn btn-danger">View Result</a>
          </div>
        </div>
      </div>

    </div>
    <div class="col mb-4">

      <div class="card" style="width: 18rem; height: 23rem;">
        <div class="zoom">
          <img src="https://t3.ftcdn.net/jpg/03/22/02/90/240_F_322029005_GPIGKrc2R9zzcU2foU1GkbIucma54J0B.jpg"
            class="card-img-top" alt="...">
        </div>
        <div class="card-body">
          <h5 class="card-title">Add Teacher</h5>
          <p class="card-text">Add teacher so to get access to the exams created by them</p>
          <div class="zoom">

            <a href="{{url_for('student.add_teacher')}}" style="width: 15.25rem; margin-top:15px;"
              class="btn btn-danger">Add Teacher</a>
          </div>
        </div>
      </div>



    </div>
    <div class="col mb-4">

      <div class="card" style="width: 18rem; height: 23rem;">
        <div class="zoom">
          <img src="https://t4.ftcdn.net/jpg/02/90/44/61/240_F_290446151_BE5PueHXw3wAYvxxwcXIDwTxgrl6mRsn.jpg"
            class="card-img-top" alt="..." style="width: 286px; height:190.66px;">
        </div>
        <div class="card-body">
          <h5 class="card-title">View Performance</h5>
          <p class="card-text">Check your performance with respect to others who attepted the same quiz</p>
          <div class="zoom">

            <a href="{{url_for('student.view_performance')}}" style="width: 15.25rem; margin-top:-20px;" class="btn btn-danger">Check Result</a>
          </div>
        </div>
      </div>





    </div>
  </div>
</div>
<footer class="page-footer blue text-center " style="padding: 15px; background-color:rgba(128, 128, 128, 0.199);">

  <!--Footer Links-->
  <div class="container-fluid" style="padding: 15px;">
    <div class="row">

      <!--First column-->
      <div class="col-md-6">
        <h5 class="title mb-3">PARiKSHA</h5>
        <p>
          PARiKSHA is created with a motive of providing a unified platform to students and teachers so that the process
          of learning and its quality does not reduces in these tough times.

        </p>
      </div>
      <!--/.First column-->

      <!--Second column-->
      <div class="col">
        <h5 class="title">Contact Us</h5>

        <li><a href="#">Mail</a></li>
        <p>pariksha.contact@gmail.com</p>
        <li><a
            href="https://www.linkedin.com/posts/pulkit-vyas_onlineexamination-onlineeducation-edtech-activity-6716777003296555008-MvzC">LinkedIn</a>
        </li>



      </div>
      <!--/.Second column-->
    </div>
  </div>

</footer>

</div>


{% endblock content %}

pariksha/student/templates/view_result.html
{% extends "layout.html" %}
{% block content%}
<style>
  .zoom {

    transition: transform .2s;
    /* Animation */
  }

  .zoom:hover {
    transform: scale(1.2);
    /* (150% zoom - Note: if the zoom is too large, it will go outside of the viewport) */
  }

  .button2:hover {
    box-shadow: 0 12px 16px 0 rgba(0, 0, 0, 0.24), 0 17px 50px 0 rgba(0, 0, 0, 0.19);
  }

  .po:hover {
    transition: transform .2s;
  }

  .po:hover {
    background-color: cyan;
  }
</style>
<div class="jumbotron" style="margin-top: 50px; background-color:white;">

  <div class="jumbotron" style=" background-color:pink; ">
    <!--the Pink box with border-->

    <!--<div class="jumbotron" style=" background-color:pink; border-radius:black solid;">-->
    <h2>All Active Quizzes Result Are Listed Below</h2>


  </div>
  <!-- The jumbotron just below this can be used as a container for whole the page and its contents-->
  <!-- ======  Start from here ======  -->

  {% if not(quiz_exists) %}


  <div class="jumbotron" style="background-color: white;  ">
    <div class="d-flex justify-content-center">
      <h1>You Haven't Attempted Any Quiz Yet</h1>
    </div>
    <div class="d-flex justify-content-center">
      <h3>Your marks will be shown once you complete a quiz...<h3>
    </div>
  </div>
  <hr style="width:100%;text-align:left;margin-left:0; width:10px;">
  {% endif %}

  {% for quiz in quiz_list %}


  <div class="jumbotron" style="background-color:rgba(128, 128, 128, 0);">

    <div class="example hoverable">

      <div class="container">
        <div class="row">
          <div class="col" id="po" style="background-color:mistyrose;  ">



            <h4 class="pt-3 pl-3"><strong>Quiz Title : {{quiz.title}} <span class="ml-5 pl-5" style="color:deeppink;">
                  Marks :
                  {{quiz.marks}}/{{quiz.total_marks}}</span></strong>
            </h4>
            <!-- yeh Next div is left in h5 please keep the suitable one
            <h5 class="pt-3 pl-3"><strong>Quiz Title : {{quiz.title}} <span class="ml-5 pl-5"> Marks :
              {{quiz.marks}}</span></strong>
        </h5>-->
          </div>




          <div class="col col-lg-2" style="background-color: mistyrose; padding:20px; ">


            <div class="example hoverable zoom">
              <a type="button" class="btn btn-success" href="{{url_for('student.view_performance')}}"
                style="width: 150px; margin-top:-4px; margin-left:px; background-color:#e43c5c;">View Performance</a>

            </div>
          </div>
        </div>
      </div>
      <hr style="width:100%;text-align:left;margin-left:0; width:10px;">
    </div><!-- <==== end here-->
    {% endfor %}
  </div>
</div>


<footer class="page-footer blue text-center " style="padding: 15px; background-color:rgba(128, 128, 128, 0.199);">

  <!--Footer Links-->
  <div class="container-fluid" style="padding: 15px;">
    <div class="row">

      <!--First column-->
      <div class="col-md-6">
        <h5 class="title mb-3">PARiKSHA</h5>
        <p>
          PARiKSHA is created with a motive of providing a unified platform to students and teachers so that the process
          of learning and its quality does not reduces in these tough times.

        </p>
      </div>
      <!--/.First column-->

      <!--Second column-->
      <div class="col">
        <h5 class="title">Contact Us</h5>

        <li><a href="#">Mail</a></li>
        <p>pariksha.contact@gmail.com</p>
        <li><a
            href="https://www.linkedin.com/posts/pulkit-vyas_onlineexamination-onlineeducation-edtech-activity-6716777003296555008-MvzC">LinkedIn</a>
        </li>



      </div>
      <!--/.Second column-->
    </div>
</div>

</footer>

</div>
{% endblock content %}